PORT=4000
GOOGLE_CLIENT_ID=xxx

JWT_PRIVATE_KEY=-----BEGIN PRIVATE KEY-----
JWT_PUBLIC_KEY=-----BEGIN PUBLIC KEY-----

ACCESS_TOKEN_EXP=15m
REFRESH_TOKEN_EXP_DAYS=30

DATABASE_URL=postgres://...
REDIS_URL=redis://...
